# Generated by Django 4.0.1 on 2022-01-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=75)),
                ('synopsys', models.TextField(max_length=300)),
                ('released', models.BooleanField(default=True)),
                ('castAndCrew', models.TextField(max_length=200)),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
    ]
