# Generated by Django 4.0.1 on 2022-01-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieListBE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
